disabled_rules:
  - line_length
  # - trailing_whitespace
  - unused_closure_parameter
  - force_cast
  - nesting
  - redundant_string_enum_value
  - variable_name

excluded: # paths to ignore during linting. overridden by `included`.
  - Pods
  - R.generated.swift
vertical_whitespace:
  max_empty_lines: 2
